/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/users": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          deleted_at?: parameters["rowFilter.users.deleted_at"];
          is_deleted?: parameters["rowFilter.users.is_deleted"];
          firstname?: parameters["rowFilter.users.firstname"];
          middlename?: parameters["rowFilter.users.middlename"];
          lastname_father?: parameters["rowFilter.users.lastname_father"];
          lastname_mother?: parameters["rowFilter.users.lastname_mother"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["users"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** users */
          users?: definitions["users"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          deleted_at?: parameters["rowFilter.users.deleted_at"];
          is_deleted?: parameters["rowFilter.users.is_deleted"];
          firstname?: parameters["rowFilter.users.firstname"];
          middlename?: parameters["rowFilter.users.middlename"];
          lastname_father?: parameters["rowFilter.users.lastname_father"];
          lastname_mother?: parameters["rowFilter.users.lastname_mother"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.users.id"];
          created_at?: parameters["rowFilter.users.created_at"];
          updated_at?: parameters["rowFilter.users.updated_at"];
          deleted_at?: parameters["rowFilter.users.deleted_at"];
          is_deleted?: parameters["rowFilter.users.is_deleted"];
          firstname?: parameters["rowFilter.users.firstname"];
          middlename?: parameters["rowFilter.users.middlename"];
          lastname_father?: parameters["rowFilter.users.lastname_father"];
          lastname_mother?: parameters["rowFilter.users.lastname_mother"];
        };
        body: {
          /** users */
          users?: definitions["users"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Table with User information */
  users: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id?: number;
    /** Format: timestamp without time zone */
    created_at?: string;
    /** Format: timestamp without time zone */
    updated_at?: string;
    /** Format: timestamp without time zone */
    deleted_at?: string;
    /** Format: boolean */
    is_deleted?: boolean;
    /** Format: text */
    firstname?: string;
    /** Format: text */
    middlename?: string;
    /** Format: text */
    lastname_father?: string;
    /** Format: text */
    lastname_mother?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description users */
  "body.users": definitions["users"];
  /** Format: bigint */
  "rowFilter.users.id": string;
  /** Format: timestamp without time zone */
  "rowFilter.users.created_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.users.updated_at": string;
  /** Format: timestamp without time zone */
  "rowFilter.users.deleted_at": string;
  /** Format: boolean */
  "rowFilter.users.is_deleted": string;
  /** Format: text */
  "rowFilter.users.firstname": string;
  /** Format: text */
  "rowFilter.users.middlename": string;
  /** Format: text */
  "rowFilter.users.lastname_father": string;
  /** Format: text */
  "rowFilter.users.lastname_mother": string;
}

export interface operations {}

export interface external {}
